config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  devise_for :users
  resources :tasks
  resources :items
  
  post 'tasks/:id/state_plus_one' => 'tasks#state_plus_one'

  get 'pages/index'
  get 'pages' => 'pages#index'
  get 'monsters' => 'monster_model#index'
  get 'monsters/new' => 'monster_model#new'
  post 'monsters/create' => 'monster_model#create'
  get 'monsters/:id' => 'monster_model#show'
  get 'monsters/:id/edit' => 'monster_model#edit'
  patch 'monsters/update' => 'monster_model#update'
  post 'monsters/:id/destroy' => 'monster_model#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/monster_model.rb
class MonsterModel < ApplicationRecord
	
end

app/models/task.rb
class Task < ApplicationRecord
	enum state: [:not_started_yet, :in_progress,:done] 
	belongs_to :user, optional: true
	mount_uploader :image, ImageUploader


	def deadline_over?
		Date.today > deadline
	end

	

	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable

  has_many :tasks, dependent: :destroy

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_in_path_for(resource)
    tasks_path
  end

  def after_sign_out_path_for(resource)
    new_user_session_url
  end


    private
    def sign_in_required
        redirect_to new_user_session_url unless user_signed_in?
    end

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description)
    end
end

app/controllers/monster_model_controller.rb
class MonsterModelController < ApplicationController
	def index
		@monsters = MonsterModel.all
	end

	def show
		@monster = MonsterModel.find_by(id: params[:id])
	end

	def new

	end

	def create
		@monster = MonsterModel.create(
			name: params[:name],
			Offensive_power: params[:Offensive_power],
			Defense_power: params[:Defense_power]
		)
		redirect_to("/monsters")
	end

	def update
		@monster = MonsterModel.find_by(id: params[:id])
		@monster.update(
			name: params[:name],
			Offensive_power: params[:Offensive_power],
			Defense_power: params[:Defense_power]
		)
		redirect_to("/monsters")
	end

	def edit
		@monster = MonsterModel.find_by(id: params[:id])
	end

	def destroy
		@monster = MonsterModel.find_by(id: params[:id])
		@monster.destroy
        redirect_to("/monsters")
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :sign_in_required, only: [:show]
  def index
  	
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :state_plus_one]
  before_action :sign_in_required

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(user_id: current_user.id)
    @search = @tasks.search(params[:q])
    @tasks = @search.result(distinct: true)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
   
    respond_to do |format|
      if @task.save
        NotificationMailer.send_confirm_to_user(@task).deliver_later
        format.html { redirect_to @task, notice: 'タスクを追加しました' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'タスクを更新しました' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
    @post = Post.new(permit_params)
    @post.save!
    redirect_to action: 'show'
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'タスクを削除しました' }
      format.json { head :no_content }
    end
  end
 
  def state_plus_one
    if @task.state == "not_started_yet"
      @task.state = "in_progress"
    elsif @task.state == "in_progress"
      @task.state = "done"
    end
    @task.save
    redirect_to tasks_url, notice: '更新しました' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :deadline, :detail, :time, :state, :image)
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/monster_model_helper.rb
module MonsterModelHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="top-bar">あああ
        <div class="top_bar_inner">
          <% if user_signed_in? %>
            <div class="top_bar_left">
              <strong><%= link_to current_user.username, tasks_path %></strong>
            </div>
            <div class="top_bar_right">
              <div class="new_task">
                <%= link_to new_task_path do %>
                <i class="fa fa-plus-circle"></i>
                <% end %>
              </div>
              <div class="profile">
                <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user-circle"></i>
                <% end %>
              </div>
              <div class="logout">
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="header_logout">
              <%= link_to '新規登録', new_user_registration_path %>
              <%= link_to 'ログイン', new_user_session_path %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

    <%= yield %>

  </body>
</html>

app/views/monster_model/edit.html.erb
<p>編集</p>
<%= form_tag({action:"update"}, {method:"patch"})do %>
  <input type="hidden" value="<%= @monster.id %>" name="id" >
  <table name="content">
    <tr>
  	  <td align="right">モンスターの名前：</td>
  	  <td><input type="text" value="<%= @monster.name %>" name="name" ></td>
    </tr>
    <tr>
  	  <td align="right">攻撃力：</td>
  	  <td><input type="number" value="<%= @monster.Offensive_power %>" name="Offensive_power"></td>
    </tr>
    <tr>
  	  <td align="right">防御力：</td>
  	  <td><input type="number" value="<%= @monster.Defense_power %>" name="Defense_power"></td>
    </tr>
    <tr>
  	  <td></td>
  	  <td>
        <div class="form">
          <input type="submit" value="新規作成">
        </div>
      </td>  
    </tr>
  </table>
<% end %>

app/views/monster_model/index.html.erb
<p>一覧ページ予定地</p>
<% @monsters.each do |monster| %>
	<%= monster.id %>
	<%= link_to(monster.name,"/monsters/#{monster.id}") %>
	<%= monster.Offensive_power %>
	<%= monster.Defense_power %>
	<br>
	
<% end %>
<%= link_to( "新規作成" ,"/monsters/new") %>

app/views/monster_model/new.html.erb
<p>新規作成</p>
<%= form_tag("/monsters/create")do %>
  <table name="content">
    <tr>
  	  <td align="right">モンスターの名前：</td>
  	  <td><input type="text" name="name"></td>
    </tr>
    <tr>
  	  <td align="right">攻撃力：</td>
  	  <td><input type="number" name="Offensive_power"></td>
    </tr>
    <tr>
  	  <td align="right">防御力：</td>
  	  <td><input type="number" name="Defense_power"></td>
    </tr>
    <tr>
  	  <td></td>
  	  <td>
        <div class="form">
          <input type="submit" value="新規作成">
        </div>
      </td>  
    </tr>
  </table>
<% end %>

app/views/monster_model/show.html.erb
<p>単独</p>
<%= @monster.name %>
<%= @monster.Offensive_power %>
<%= @monster.Defense_power %>

<br>
<%= link_to("edit","/monsters/#{@monster.id}/edit") %>
<%= link_to("destroy","/monsters/#{@monster.id}/destroy",
	{method: "post"}) %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<p>お腹すいた</p>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="add_task_list">
    <div class="field">
      <%= form.label :name, "名前" %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :deadline, "期日" %>
      <%= form.datetime_select :deadline %>
    </div>

    <div class="field">
      <%= form.label :detail, "詳細" %>
      <%= form.text_area :detail %>
    </div>

    <div class="field">
      <%= form.label :time, "かかる時間" %>
      <%= form.number_field :time %>
    </div>

    <div class="field">
      <%= form.label :image, "画像" %>
      <%= form.file_field :image, id: :task_image %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>


<% end %>

app/views/tasks/edit.html.erb
<div class="task_edit">
	<div class="edit_wrapper">
		<div class="edit_list">
			<h1>タスク編集</h1>

			<%= render 'form', task: @task %>
            <div class="edit_icon">
				<%= link_to @task do %>
				<i class="fa fa-bars"></i>
                <% end %>
                 |
				<%= link_to tasks_path do %>
					<i class="fa fa-home"></i>
		        <% end %>
			</div>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="content_wrapper">
  <div class="search_form">
    <%= search_form_for @search do |f| %>
      <div class="form_group">
        <div class="form_name">
          <%= f.label :name_cont, "名前" %>
          <%= f.text_field :name_cont, class: "form_control" %>
        </div>
        <div class="form_state">
          <%= f.label :state_eq,  "進捗" %>
          <%= f.select :state_eq, [["not_started_yet", 0],["in_progress", 1],["done", 2]] , :include_blank => '指定なし', class: "form_control" %>
        </div>
      </div>

      <div class="actions"><%= f.submit "検索" %></div>
    <% end %>
    
    <div class="new_task">
      <%= link_to 'タスクを追加', new_task_path %>
    </div>
  </div>

  <div class="task_list">
      <tbody>
        <table class="task_table_true">
      <thead>
        <tr>
          <th>名前</th>
          <th>期日</th>
          <th>進捗</th>
          <th>ボタン</th>
          <th>画像</th>
          <th colspan="3"></th>
        </tr>
      </thead>
        <h2 class="task_over_header">期限切れ</h2>
        <% @tasks.each do |task| %>
        <% if task.deadline_over? == true %>
          <tr>
              <td><%= task.name  %></td>
              <td>
                  <span style="border-bottom: #db4c3f 1px solid">
                    <%= task.deadline.strftime("%Y-%m-%d %H:%M") %>
                  </span>
              </td>
              <td><%= task.state %></td>
              <td class="state_td">
                <% if task.state == "not_started_yet" %> 
                <%= button_to '着手', "/tasks/#{task.id}/state_plus_one",class: "font10" %>
                <% elsif task.state == "in_progress" %>
                <%= button_to '進行中', "/tasks/#{task.id}/state_plus_one",class: "font10" %>
                <% end %>
              </td>
              <td class="image_td">
                <%= image_tag(task.image_url , :class => "thumbnail") if task.image.present? %>
              </td>
              <td><%= link_to task do %>
                <i class="fa fa-bars"></i>
                <% end %>
              </td>
              <td><%= link_to edit_task_path(task) do %>
                <i class="fa fa-edit"></i>
                <% end %>
              </td>
              <td><%= link_to task, method: :delete, data: { confirm: '本当に削除しますか？' } do %>
                <i class="fa fa-minus-circle"></i>
                <% end %>
              </td>
          </tr>
          <% end %>
        <% end %>         
        <table class="task_table_false">
          <h2 class="task_list_header">タスク</h2>
          <thead>
            <tr>
              <th>名前</th>
              <th>期日</th>
              <th>進捗</th>
              <th>ボタン</th>
              <th>画像</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @tasks.each do |task| %>
          <% if task.deadline_over? == false %>
          <tr>
              <td><%= task.name  %></td>
              <td>
                <%= task.deadline.strftime("%Y-%m-%d %H:%M") %>
              </td>
              <td><%= task.state %></td>
              <td class="state_td">
                <% if task.state == "not_started_yet" %> 
                <%= button_to '着手', "/tasks/#{task.id}/state_plus_one",class: "font10" %>
                <% elsif task.state == "in_progress" %>
                <%= button_to '進行中', "/tasks/#{task.id}/state_plus_one",class: "font10" %>
                <% end %>
              </td>
              <td class="image_td">
                <%= image_tag(task.image_url , :class => "thumbnail") if task.image.present? %>
              </td>
              <td><%= link_to task do %>
                <i class="fa fa-bars"></i>
                <% end %>
              </td>
              <td><%= link_to edit_task_path(task) do %>
                <i class="fa fa-edit"></i>
                <% end %>
              </td>
              <td><%= link_to task, method: :delete, data: { confirm: '本当に削除しますか？' } do %>
                <i class="fa fa-minus-circle"></i>
                <% end %>
              </td>
          </tr>
          <% end %>
        <% end %> 
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="add_task">
	<div class="add_task_wrapper">
		<h1>タスクを追加</h1>

		<%= render 'form', task: @task %>

		<%= link_to tasks_path do %>
		<i class="fa fa-home"></i>
		<% end %>
    </div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show_wrapper">
  <div class="show_list">
      <h2 class="show_state">詳細ページ</h2>
      <p>
        <strong>名前:</strong>
        <%= @task.name %>
      </p>

      <p>
        <strong>期日:</strong>
        <%= @task.deadline.strftime("%Y-%m-%d %H:%M") %>
      </p>
      超えてる？
      <%= @task.deadline_over? %>

      <p>
        <strong>詳細:</strong>
        <%= @task.detail %>
      </p>

      <p>
        <strong>かかる予定時間:</strong>
        <%= @task.time %>
      </p>

      <p>
        <strong>進捗:</strong>
        <%= @task.state %>
      </p>

      <p>
        <strong>ボタン:</strong>
        <% if @task.state == "not_started_yet" %> 
          <%= button_to '着手', "/tasks/#{@task.id}/state_plus_one" %>
          <% elsif @task.state == "in_progress" %>
          <%= button_to '進行中', "/tasks/#{@task.id}/state_plus_one" %>
        <% end %>
      </p>

      <p>
        <strong>画像:</strong>
        <%= image_tag(@task.image_url, :class => "thumbnail") if @task.image.present? %>
      </p>

      <div class="show_icon">
        <%= link_to edit_task_path(@task) do %>
          <i class="fa fa-edit"></i>
        <% end %> |
        <%= link_to tasks_path do %>
          <i class="fa fa-home"></i>
        <% end %>
      </div>
  </div>
</div>